# Fish completion for update-anything.
# Install location (auto-detected by install.sh): ~/.config/fish/completions/update-anything.fish

complete -c update-anything -s y -l yes -d 'Skip confirmation prompts'
complete -c update-anything -s c -l check -d 'Dry run, change nothing'
complete -c update-anything -l clean -d 'Clean package cache'
complete -c update-anything -l orphans -d 'Remove orphaned packages'
complete -c update-anything -l firmware -d 'Check/apply firmware updates'
complete -c update-anything -l snapshot -d 'Create a system-level snapshot before updating'
complete -c update-anything -l deep-clean -d 'Prune dev/container caches after updating'
complete -c update-anything -l inhibit-sleep -d 'Prevent the system from sleeping while this runs'
complete -c update-anything -l audit -d 'Run vulnerability-audit tools before updating'
complete -c update-anything -l rollback -d 'Show a diff between the last two package snapshots and exit'
complete -c update-anything -l notify -d 'Send desktop notification when done'
complete -c update-anything -l only -x -a 'pacman apt dnf yum zypper apk brew macports pkg pkg_add flatpak snap nix cargo npm pipx uv pnpm bun' -d 'Update only these managers'
complete -c update-anything -s q -l quiet -d 'Print only warnings and errors'
complete -c update-anything -l no-parallel -d 'Run user-space managers one at a time'
complete -c update-anything -l full -d 'Print every pending update, not just the first 20'
complete -c update-anything -l no-pacman -d 'Skip pacman + AUR'
complete -c update-anything -l no-apt -d 'Skip apt'
complete -c update-anything -l no-dnf -d 'Skip dnf'
complete -c update-anything -l no-yum -d 'Skip yum'
complete -c update-anything -l no-zypper -d 'Skip zypper'
complete -c update-anything -l no-apk -d 'Skip apk'
complete -c update-anything -l no-brew -d 'Skip Homebrew'
complete -c update-anything -l no-macports -d 'Skip MacPorts'
complete -c update-anything -l no-pkg -d 'Skip FreeBSD pkg'
complete -c update-anything -l no-pkg_add -d 'Skip OpenBSD pkg_add'
complete -c update-anything -l no-flatpak -d 'Skip Flatpak'
complete -c update-anything -l no-snap -d 'Skip Snap'
complete -c update-anything -l no-nix -d 'Skip Nix'
complete -c update-anything -l no-cargo -d 'Skip cargo'
complete -c update-anything -l no-npm -d 'Skip npm'
complete -c update-anything -l no-pipx -d 'Skip pipx'
complete -c update-anything -l no-uv -d 'Skip uv'
complete -c update-anything -l no-pnpm -d 'Skip pnpm'
complete -c update-anything -l no-bun -d 'Skip bun'
complete -c update-anything -s h -l help -d 'Show help'
complete -c update-anything -s v -l version -d 'Show version'
